# Generated by Django 4.2 on 2023-07-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('nick_name', models.CharField(max_length=4)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('captain_name', models.CharField(max_length=25)),
                ('started_year', models.IntegerField(max_length=4)),
            ],
        ),
    ]
