# Generated by Django 4.2 on 2023-07-18 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='team_info',
            table='team_info',
        ),
    ]
