# Generated by Django 4.2.2 on 2023-07-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0003_registereduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterModelTable(
            name='registereduser',
            table='registereduser',
        ),
    ]
